### ISSUE TITLE
Different implementation of DGCNN

### ISSUE THREAD

**Issue by HeliosZhao** [IdanAchituve/DefRec_and_PCM#13]
Thanks for your code. It is a really interesting work.

I found your implementation of DGCNN is different from [the official implementation](https://github.com/WangYueFt/dgcnn/blob/e96a7e26555c3212dbc5df8d8875f07228e1ccc2/pytorch/model.py#L88). It seems that you use the top branch of the segmentation network of DGCNN instead of the classification work.

The classification work may not contain the transform net and the embedding feature is the concatenation of the max pooling and average pooling features.

Is that right?

**Comment by IdanAchituve** [comment]
Hi Zhao,
Thanks for taking interest. 
Indeed there are some  discrepancies between my version and the official PyTorch version. Note that in their implementation as well there is a discrepancy between the PyTroch and TensorFlow versions. I tried to stay consistent with the TensorFlow version and the architecture as published in the paper for both the classification task (PointDA; top branch in Fig. 3 in their paper) and the segmentation task (PointSegDA; bottom branch in Fig. 3 in their paper). 

Cheers,
Idan

**Comment by HeliosZhao** [comment]
Hi, @IdanAchituve,

Thanks for your quick reply.

I check the TensorFlow version of DGCNN. Yeah, it is the same with you. Also, this version is the classification network described in the DGCNN paper.

By the way, I think it is better to change your default argparse of [DefRec_on_src](https://github.com/IdanAchituve/DefRec_and_PCM/blob/04c41bab919ef17fe3b36d361e4b97f30abbca7c/PointDA/trainer.py#L55) to False, which is the same with your paper and also achieves better performance.

**Comment by IdanAchituve** [comment]
Good idea. Thanks :-)
