### ISSUE TITLE
Experiment results in this paper

### ISSUE THREAD

**Issue by zou-longkun** [IdanAchituve/DefRec_and_PCM#4]
I noticed that the experiment results of "DefRec+PCM" is not consistent among Table1-4,  especially Table 4 looks better, Is it due to  the experimental settings are different, or other reasons?

**Comment by idanachi** [comment]
Hi,
Indeed there were some discrepancies between my private code and the
published code. Thanks for letting me know.
I fixed them, however, still there seems to be something different in the
randomization.
I hope to get around to it in the following weeks. The results should be
more similar now though.
Re the experimental setup, please consider that the results presented in
the paper are the average over 3 seeds.
Re Table 1-3 please note that the results are taken after a sweep over the
hyper parameters of each deformation type (e.g., radius size in volume
based deformations).

Cheers,
Idan
