### ISSUE TITLE
Results for the baseline (unsupervised) from modelNet to shapeNet

### ISSUE THREAD

**Issue by YiruS** [IdanAchituve/DefRec_and_PCM#5]
Hi, 

Nice work and thanks for sharing the code!

I have one question regarding the baseline results from ModelNet to ShapeNet. It seems that the baseline already achieved 83.3%. However in PointDA, the baseline is 42.5%. Also I noticed that the data for training are different -- the alignment has been done in your dataset. Would that be the reason for the significant improvement for that baseline?

Thanks!

**Comment by idanachi** [comment]
Hi,
Thanks :-)
Indeed the alignment had a huge effect on the domain gap.
PointDA considered it as part of the gap. We didn't and therefore we tried
to align the shapes.
Also, the experimental setup in their paper is quite different than ours.
For example, we selected hyper-parameters based on the source validation
set while they didn't.

Cheers,
Idan
