### ISSUE TITLE
How to launch training

### ISSUE THREAD

**Issue by adricarda** [IdanAchituve/DefRec_and_PCM#7]
Hi, thank you for your work.
I am getting this error 

Traceback (most recent call last):
  File "PointDA/trainer.py", line 12, in <module>
    import utils.log
ModuleNotFoundError: No module named 'utils'

when using this command:
python PointDA/trainer.py

**Comment by IdanAchituve** [comment]
Hi,
Did you install the repo? It shouldn't happen after you install it.

Cheers,
Idan

**Comment by adricarda** [comment]
yes thank you it works after installation
