### ISSUE TITLE
About the experiments results are greatly different from the default paraments.

### ISSUE THREAD

**Issue by queenie88** [IdanAchituve/DefRec_and_PCM#9]
Dear Idan，

I use the default parameters to run the code about PointSegDA task. The results are greatly different from those on the paper. Such as the results of FAUST to MIT mIOU: 0.6211 , in paper is 79.7 ± 0.3,MIT to FAUST our mIOU: 0.4400, in paper is 67.1 ± 1.0 .  The results are very different, could you please help me to explain what causes it.
Could you show the paraments with the DefRec_weight, noisy_std, and so on.

**Comment by IdanAchituve** [comment]
Hi,
It appears you are right. There is a mistake in the column labeling of Table 4 in the paper.
the results for FAUST to MIT should be replaced with the results for FAUST to ADOBE and vice-versa,
the results for MIT to FAUST should be replaced with the results for MIT to ADOBE and vice-versa,
and finally, SCAPE to FAUST should be replaced with SCAPE to ADOBE, SCAPE to MIT should be replaced with SCAPE to FAUST and SCAPE to ADOBE should be replaced with SCAPE to MIT.
I will fix that in the arxiv version of the paper.

Thanks,
Idan
